config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    # https://github.com/spree/spree/blob/3-0-stable/backend/config/routes.rb#L73
    resources :orders do
      resources :bookkeeping_documents, only: :index do
        get 'refresh', on: :collection
      end
    end

    resource :print_invoice_settings, only: [:edit, :update]
    resources :bookkeeping_documents, only: [:index, :show]
  end
end

app/models/spree/bookkeeping_document.rb
module Spree
  class BookkeepingDocument < ActiveRecord::Base
    PERSISTED_ATTRS = [
      :firstname,
      :lastname,
      :email,
      :total,
      :number
    ]

    # Spree::BookkeepingDocument cares about creating PDFs. Whenever it needs to know
    # anything about the document to send to the view, it asks a view object.
    #
    # +printable+ should be an Object, such as Spree::Order or Spree::Shipment.
    # template should be a string, such as "invoice" or "packaging_slip"
    #
    belongs_to :printable, polymorphic: true
    validates :printable, :template, presence: true
    validates *PERSISTED_ATTRS, presence: true, if: -> { self.persisted? }
    scope :invoices, -> { where(template: 'invoice') }

    before_create :copy_view_attributes
    after_save :after_save_actions

    # An instance of Spree::Printable::#{YourModel}::#{YourTemplate}Presenter
    #
    def view
      @_view ||= view_class.new(printable)
    end

    def date
      created_at.to_date
    end

    def template_name
      "spree/printables/#{single_lower_case_name(printable.class.name)}/#{template}"
    end

    # If the document is called from the view with some method it doesn't know,
    # just call the view object. It should know.
    def method_missing(method_name, *args, &block)
      if view.respond_to? method_name
        view.send(method_name, *args, &block)
      else
        super
      end
    end

    def document_type
      "#{printable_type.demodulize.tableize.singularize}_#{template}"
    end

    # Returns the given template as pdf binary suitable for Rails send_data
    #
    # If the file is already present it returns this
    # else it generates a new file, stores and returns this.
    #
    # You can disable the pdf file generation with setting
    #
    #   Spree::PrintInvoice::Config.store_pdf to false
    #
    def pdf
      if Spree::PrintInvoice::Config.store_pdf
        send_or_create_pdf
      else
        render_pdf
      end
    end

    # = The PDF file_name
    #
    def file_name
      @_file_name ||= "#{template}-D#{id}-N#{number}.pdf"
    end

    # = PDF file path
    #
    def file_path
      @_file_path ||= Rails.root.join(storage_path, "#{file_name}")
    end

    # = PDF storage folder path for given template name
    #
    # Configure the storage path with +Spree::PrintInvoice::Config.storage_path+
    #
    # Each template type gets it own pluralized folder inside
    # of +Spree::PrintInvoice::Config.storage_path+
    #
    # == Example:
    #
    #   storage_path('invoice') => "tmp/pdf_prints/invoices"
    #
    # Creates the folder if it's not present yet.
    #
    def storage_path
      storage_path = Rails.root.join(Spree::PrintInvoice::Config.storage_path, template.pluralize)
      FileUtils.mkdir_p(storage_path)
      storage_path
    end

    # Renders the prawn template for give template name in context of ActionView.
    #
    # Prawn templates need to be placed in the correct folder. For example, for a PDF from
    # a Spree::Order with the invoice template, it would be
    # the +app/views/spree/printables/order/invoices+ folder.
    #
    # Assigns +@doc+ instance variable
    #
    def render_pdf
      ApplicationController.render(
        template: "#{template_name}.pdf.prawn",
        assigns: { doc: self }
      )
    end

    private

    def copy_view_attributes
      PERSISTED_ATTRS.each do |attr|
        send("#{attr}=", view.send(attr))
      end
    end

    # For a Spree::Order printable and an "invoice" template,
    # you would get "spree/documents/order/invoice_view"
    # --> Spree::Printables::Order::InvoiceView
    #
    def view_class
      @_view_class ||= "#{template_name}_view".classify.constantize
    end

    def single_lower_case_name(class_string)
      @_single_lower_class_name ||= class_string.demodulize.tableize.singularize
    end

    # Sends stored pdf for given template from disk.
    #
    # Renders and stores it if it's not yet present.
    #
    def send_or_create_pdf
      unless File.exist?(file_path)
        File.open(file_path, 'wb') { |f| f.puts render_pdf }
      end

      IO.binread(file_path)
    end
  end
end

app/controllers/spree/admin/bookkeeping_documents_controller.rb
module Spree
  module Admin
    class BookkeepingDocumentsController < ResourceController
      before_action :load_order, if: :order_focused?

      helper_method :order_focused?

      def show
        respond_with(@bookkeeping_document) do |format|
          format.pdf do
            send_data @bookkeeping_document.pdf, type: 'application/pdf', disposition: 'inline'
          end
        end
      end

      def index
        # Massaging the params for the index view like Spree::Admin::Orders#index
        params[:q] ||= {}
        @search = Spree::BookkeepingDocument.ransack(params[:q])
        @bookkeeping_documents = @search.result
        @bookkeeping_documents = @bookkeeping_documents.where(printable: @order) if order_focused?
        @bookkeeping_documents = @bookkeeping_documents.page(params[:page] || 1).per(10)
      end

      def refresh
        unless @order.nil?
          @order.bookkeeping_documents.delete_all
          @order.invoice_for_order
        end
        redirect_to action: 'index'
      end

      private

      def order_focused?
        params[:order_id].present?
      end

      def load_order
        @order = Spree::Order.find_by(number: params[:order_id])
      end
    end
  end
end

app/views/spree/admin/bookkeeping_documents/index.html.erb
<% if order_focused? %>
  <%= render partial: 'spree/admin/shared/order_tabs', locals: { current: :documents } %>

  <% content_for :page_actions do %>
    <%= button_link_to(Spree.t(@bookkeeping_documents.any? ? :refresh_documents : :create_documents), spree.refresh_admin_order_bookkeeping_documents_path(@order), { class: "btn-primary", icon: @bookkeeping_documents.any? ? 'refresh' :'add', id: 'refresh-bookkeeping' }) %>
  <% end %>

  <% content_for :page_title do %>
    <%= t(:documents_for_order, scope: [:spree, :print_invoice], order_number: @order.number) %>
  <% end %>
<% else %>
  <% content_for :page_title do %>
    <%= t(:documents, scope: [:spree, :print_invoice]) %>
  <% end %>

  <% content_for :table_filter do %>
    <div data-hook="admin_orders_index_search">

      <%= search_form_for [:admin, @search] do |f| %>
        <%= f.hidden_field :template_type_eq, value: params[:q][:template_type_eq] %>
        <div class="row">
          <div class="date-range-filter col-md-8">
            <div class="form-group">
              <%= label_tag :q_created_at_gt, Spree.t(:date_range) %>
              <div class="row no-padding-bottom">
                <div class="col-md-6">
                  <div class="input-group">
                    <%= f.text_field :created_at_gt, class: 'datepicker datepicker-from form-control', value: params[:q][:created_at_gt], placeholder: Spree.t(:start) %>
                    <span class="input-group-addon">
                      <i class="icon icon-calendar"></i>
                    </span>
                  </div>

                </div>
                <div class="col-md-6">
                  <div class="input-group">
                    <%= f.text_field :created_at_lt, class: 'datepicker datepicker-to form-control', value: params[:q][:created_at_lt], placeholder: Spree.t(:stop) %>
                    <span class="input-group-addon">
                      <i class="icon icon-calendar"></i>
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="col-md-4">
            <div class="form-group">
              <%= label_tag :q_number_cont, Spree.t(:printable_number, number: '') %>
              <%= f.text_field :number_cont, class: 'form-control js-quick-search-target' %>
            </div>
          </div>

        </div>

        <div class="row">

          <div class="col-md-4">
            <div class="form-group">
              <%= label_tag :q_firstname_start, Spree.t(:first_name_begins_with) %>
              <%= f.text_field :firstname_start, class: 'form-control' %>
            </div>
          </div>

          <div class="col-md-4">
            <div class="form-group">
              <%= label_tag :q_lastname_start, Spree.t(:last_name_begins_with) %>
              <%= f.text_field :lastname_start, class: 'form-control' %>
            </div>
          </div>

          <div class="col-md-4">
            <div class="form-group">
              <%= label_tag :q_email_cont, Spree.t(:email) %>
              <%= f.text_field :email_cont, class: 'form-control js-filterable' %>
            </div>
          </div>

        </div>

        <div data-hook="admin_orders_index_search_buttons" class="form-actions">
          <%= button Spree.t(:filter_results), 'search' %>
        </div>

      <% end %>
    </div>

  <% end %>
  <%= render partial: 'spree/admin/shared/index_table_options', locals: { collection: @bookkeeping_documents } %>
<% end %>

<% if @bookkeeping_documents.any? %>
  <table class="table table-responsive-lg" id="listing_orders" data-hook>
    <thead>
      <tr data-hook="printables_index_headers">
        <th><%= sort_link @search, :created_at, Spree.t(:date, scope: :print_invoice) %></th>
        <th><%= sort_link @search, :template, Spree.t(:document_type, scope: :print_invoice) %></th>
        <th><%= sort_link @search, :number, Spree.t(:order_number, scope: :print_invoice) %></th>
        <th><%= sort_link @search, :firstname, Spree.t(:firstname, scope: :print_invoice) %></th>
        <th><%= sort_link @search, :lastname, Spree.t(:lastname, scope: :print_invoice) %></th>
        <th><%= sort_link @search, :email, Spree.t(:email, scope: :print_invoice) %></th>
        <th><%= sort_link @search, :total, Spree.t(:total) %></th>
        <th data-hook="admin_orders_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
    <% @bookkeeping_documents.each do |bookkeeping_document| %>
      <tr data-hook="admin_printables_index_rows" class="<%= cycle('odd', 'even') %>">
        <td><%= l bookkeeping_document.created_at.to_date %></td>
        <td><%= Spree.t(bookkeeping_document.document_type, scope: [:print_invoice]) %></td>
        <td><%= bookkeeping_document.number %></td>
        <td><%= bookkeeping_document.firstname %></td>
        <td><%= bookkeeping_document.lastname %></td>
        <td><%= bookkeeping_document.email %></td>
        <td><%= bookkeeping_document.display_total.to_html %></td>
        <td class='actions actions-1' data-hook="admin_orders_index_row_actions">
          <%= link_to_with_icon "file", "", admin_bookkeeping_document_path(bookkeeping_document, format: :pdf), title: "show_bookkeeping_document_#{bookkeeping_document.id}", no_text: true %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::BookkeepingDocument)) %>,
  </div>
<% end %>

<% unless order_focused? %>
  <%= render partial: 'spree/admin/shared/index_table_options', locals: { collection: @bookkeeping_documents, simple: true } %>
<% end %>